# GitHub Pages jekyll libraries supported with versions: https://pages.github.com/versions/
timezone: Europe/London
title: Your awesome title
email: your-email@example.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/bettys"
url: "https://klez.me/bettys"
copyright: Copyright ©  2020

sass:
    sass_dir: _sass
    style: compressed

include:
    - _pages

defaults:
    - scope:
          path: ""
      values:
          header: true
          navbar: true
          up_arrow: true
          row_wrap: true
          footer: true
          author:
              name: Author
          header_background_url: ""
    - scope:
          path: ""
          type: "posts"
      values:
          layout: "post"
          permalink: /:year/:month/:day/:title/
          post: true

show_excerpts: true
excerpt_separator: "{% include more.html %}"

comments:
    enabled: false
reading_time:
    enabled: false

markdown: kramdown
plugins:
  - github-pages
  - jekyll-feed

exclude:
    - docs/

github: [metadata]
