# GitHub Pages jekyll libraries supported with versions: https://pages.github.com/versions/
timezone: Europe/London
title: Magic Betty
email: info@magicbetty.com
description: >-
  This is the website of Roberta Scarpetti. An Applied Theatre Practitioner and Consultant specialising in autism.
baseurl: ""
url: "https://magicbetty.com"
copyright: Copyright ©  2020

sass:
    sass_dir: _sass
    style: compressed

include:
    - _pages

defaults:
    - scope:
          path: ""
      values:
          header: true
          navbar: true
          up_arrow: true
          row_wrap: true
          footer: true
          author:
              name: Author
          header_background_url: ""
    - scope:
          path: ""
          type: "posts"
      values:
          layout: "post"
          permalink: /:year/:month/:day/:title/
          post: true

show_excerpts: true
excerpt_separator: "{% include more.html %}"

comments:
    enabled: false
reading_time:
    enabled: false

markdown: kramdown
plugins:
  - github-pages
  - jekyll-feed

exclude:
    - docs/

github: [metadata]
