# GitHub Pages jekyll libraries supported with versions: https://pages.github.com/versions/
timezone: Europe/London
title: Magic Betty
email: info@magicbetty.com
description: >-
  This is the website of Roberta Scarpetti. An Applied Theatre Practitioner and Consultant specialised in autism.
baseurl: ""
url: "https://magicbetty.com"
copyright: Copyright © Alessandro Accardo 2020

about_author: >-
  Hey! If you're looking at the source code you might be a real supah h4x0r!
  
  No no, Really.
  
  I'm Alessandro a.k.a. kLeZ, the author of this web place, made with love for a friend.
  
  If you think this work could be somewhat appreciated please star the repository on github, where the source for this website is gently kept safe.
  
  If you like my works, star any other repository you may like from the list.
  
  Please feel free to contact me in one of the social channels you can find on my website (link at the bottom of the page).



sass:
    sass_dir: _sass
    style: compressed

include:
    - _pages

defaults:
    - scope:
          path: ""
      values:
          header: true
          navbar: false
          up_arrow: true
          row_wrap: true
          footer: true
          author:
              name: Betty
          header_background_url: ""
    - scope:
          path: ""
          type: "posts"
      values:
          layout: "post"
          permalink: /:year/:month/:day/:title/
          post: true

show_excerpts: true
excerpt_separator: "{% include more.html %}"

comments:
  enabled: true
  type: staticman
  post_url: https://klez-commenter.herokuapp.com/v2/entry/kLeZ/bettys/master/comments/
  avatar_provider: gravatar

  reading_time:
    enabled: false

markdown: kramdown
plugins:
  - github-pages
  - jekyll-feed

exclude:
    - docs/

github: [metadata]
